spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mydb.c0eebz3zbzjp.ap-northeast-2.rds.amazonaws.com:3306/mydb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: doctor978
  jpa:
    # Table 수정 시 ddl-auto 활성화
    hibernate:
      ddl-auto: validate
    show-sql: true
  jwt:
    header: Authorization
    secret: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
    token-validity-in-seconds: 86400 # ttl (초)
server:
  error:
    include-message: always
    include-exception: false
    include-stacktrace: never
