spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://mydb.c0eebz3zbzjp.ap-northeast-2.rds.amazonaws.com:3306/mydb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: admin
#    password: doctor978
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:manage;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: sa
    password:


  jpa:
    defer-datasource-initialization: true
    # Table 수정 시 ddl-auto 활성화
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

server:
  error:
    include-message: always
    include-exception: false
    include-stacktrace: never
